mxz_user:
    resource: "@MXZUserBundle/Resources/config/routing.yml"
    prefix:   /

mxzpcg:
    resource: "@MXZPCGBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"