MXZ\UserBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO


    oneToMany:
        campaign:
            targetEntity: Campaign
            mappedBy: gmid

    manyToMany:
        players:
            targetEntity: Campaign
            mappedBy: players